package com.briup.apps.tyd.dao;

import com.briup.apps.tyd.bean.Catalog;
import com.briup.apps.tyd.bean.CatalogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    long countByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    int deleteByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    int insert(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    int insertSelective(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    List<Catalog> selectByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    Catalog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Catalog record, @Param("example") CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    int updateByExample(@Param("record") Catalog record, @Param("example") CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    int updateByPrimaryKeySelective(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_catalog
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    int updateByPrimaryKey(Catalog record);
}