package com.briup.apps.tyd.dao;

import com.briup.apps.tyd.bean.CmsUserRole;
import com.briup.apps.tyd.bean.CmsUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    long countByExample(CmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    int deleteByExample(CmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    int insert(CmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    int insertSelective(CmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    List<CmsUserRole> selectByExample(CmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    CmsUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmsUserRole record, @Param("example") CmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    int updateByExample(@Param("record") CmsUserRole record, @Param("example") CmsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    int updateByPrimaryKeySelective(CmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Mon Nov 18 16:23:17 CST 2019
     */
    int updateByPrimaryKey(CmsUserRole record);
}