package com.briup.apps.tyd.bean;

public class Catalog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_catalog.id
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_catalog.content
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_catalog.action_time
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    private Long actionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_catalog.user_id
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_catalog.id
     *
     * @return the value of cms_catalog.id
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_catalog.id
     *
     * @param id the value for cms_catalog.id
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_catalog.content
     *
     * @return the value of cms_catalog.content
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_catalog.content
     *
     * @param content the value for cms_catalog.content
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_catalog.action_time
     *
     * @return the value of cms_catalog.action_time
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    public Long getActionTime() {
        return actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_catalog.action_time
     *
     * @param actionTime the value for cms_catalog.action_time
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    public void setActionTime(Long actionTime) {
        this.actionTime = actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_catalog.user_id
     *
     * @return the value of cms_catalog.user_id
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_catalog.user_id
     *
     * @param userId the value for cms_catalog.user_id
     *
     * @mbg.generated Tue Nov 12 14:43:56 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}