package com.briup.apps.tyd.bean;

public class CmsTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_test.id
     *
     * @mbg.generated Mon Nov 11 19:43:01 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_test.name
     *
     * @mbg.generated Mon Nov 11 19:43:01 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_test.id
     *
     * @return the value of cms_test.id
     *
     * @mbg.generated Mon Nov 11 19:43:01 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_test.id
     *
     * @param id the value for cms_test.id
     *
     * @mbg.generated Mon Nov 11 19:43:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_test.name
     *
     * @return the value of cms_test.name
     *
     * @mbg.generated Mon Nov 11 19:43:01 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_test.name
     *
     * @param name the value for cms_test.name
     *
     * @mbg.generated Mon Nov 11 19:43:01 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}